---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.0
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer install --no-progress --no-suggest

  - name: phpcs
    image: joomlaprojects/docker-images:php8.0
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
      - ./vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .
      - echo $(date)

  - name: phpstan
    image: joomlaprojects/docker-images:php8.0
    failure: ignore
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/phpstan analyse src tests
      - echo $(date)

  - name: php80
    depends_on: [ phpcs ]
    failure: ignore
    image: joomlaprojects/docker-images:php8.0
    commands:
      - php -v
      - ./vendor/bin/phpunit --configuration=phpunit.xml

  - name: php81
    depends_on: [ phpcs ]
    failure: ignore
    image: joomlaprojects/docker-images:php8.1
    commands:
      - php -v
      - ./vendor/bin/phpunit --configuration=phpunit.xml

  - name: php82
    depends_on: [ phpcs ]
    failure: ignore
    image: joomlaprojects/docker-images:php8.2
    commands:
      - php -v
      - ./vendor/bin/phpunit --configuration=phpunit.xml

  - name: deployment
    image: appleboy/drone-ssh
    depends_on:
      - php80
    settings:
      host:
        from_secret: jissues_host
      username:
        from_secret: jissues_username
      port: 22
      key:
        from_secret: jissues_key
      script:
        - bin/jtracker update:server --log=cron.log
    when:
      branch:
        - master
      status:
        - success
      event:
        - push

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 51d49e217eb34b3b077fc88c5dda43b3654ff3c17f1cf66f706d34670ce9d7a9

...
