---
kind: pipeline
name: default

clone:

steps:
  - name: deploy-test
    image: joomlaprojects/docker-images:php7.3
    environment:
      JHOST:
        from_secret: jissues_host
      JUSERNAME:
        from_secret: jissues_username
      JKEY:
        from_secret: jissues_key
    commands:
      - TEMP=$(mktemp)
      - echo "$JKEY" > $TEMP
      - ssh -o 'StrictHostKeyChecking no' -i $TEMP $JUSERNAME@$JHOST 'bash -s'

---
kind: signature
hmac: d2434b64a8bdf72f0bec17b945ba6557d1a223fb2cb4c1a00ce98cbd83e6595d

...
