---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php7.4
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer install --no-progress --no-suggest

  - name: phpcs
    image: joomlaprojects/docker-images:php7.4
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
      - ./vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .
      - echo $(date)

  - name: phpstan
    image: joomlaprojects/docker-images:php7.4
    failure: ignore
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/phpstan analyse src tests cli
      - echo $(date)

  - name: php74
    depends_on: [ phpcs ]
    image: joomlaprojects/docker-images:php7.4
    commands:
      - php -v
      - ./vendor/bin/phpunit --configuration=phpunit.xml

  - name: php80
    depends_on: [ phpcs ]
    failure: ignore
    image: joomlaprojects/docker-images:php8.0
    commands:
      - php -v
      - ./vendor/bin/phpunit --configuration=phpunit.xml

  - name: php81
    depends_on: [ phpcs ]
    failure: ignore
    image: joomlaprojects/docker-images:php8.1
    commands:
      - php -v
      - ./vendor/bin/phpunit --configuration=phpunit.xml

  - name: deployment
    image: appleboy/drone-ssh
    depends_on:
      - php74
    settings:
      host:
        from_secret: jissues_host
      username:
        from_secret: jissues_username
      port: 22
      key:
        from_secret: jissues_key
      script:
        - bin/jtracker update:server --log=cron.log
    when:
      branch:
        - master
      status:
        - success
      event:
        - push

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 52d4d6492e6060882b25d6eac8e86d78a3e49bcca526fcf4b00e3c7b4a8246f0

...
