<?php
namespace Joomla\Tracker\Authentication\GitHub;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-04 at 15:50:43.
 */
class GitHubUserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GitHubUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GitHubUser;
    }

    /**
     */
    public function testLoadGitHubData()
    {
	    $ghData = new \stdClass;

	    $ghData->login = 'elkuku';
	    $ghData->avatar_url = 'http://my_avatar.png';

	    $this->object->loadGitHubData($ghData);

	    $this->assertThat(
		    $this->object->username,
		    $this->equalTo('elkuku')
	    );

	    $this->assertThat(
		    $this->object->name,
		    $this->equalTo('elkuku')
	    );

	    $this->assertThat(
		    $this->object->email,
		    $this->equalTo('email@example.com')
	    );
    }

	/**
	 * @expectedException \RuntimeException
	 */
	public function testLoadGitHubDataFailure()
	{
		$ghData = new \stdClass;

		// Missing login !

		$this->object->loadGitHubData($ghData);
	}
}
